// <auto-generated />
namespace Reddit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IndividualVoteIncrimients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IndividualVoteIncrimients));
        
        string IMigrationMetadata.Id
        {
            get { return "201508030346472_IndividualVoteIncrimients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
