// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedseedmethodforarticles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedseedmethodforarticles));
        
        string IMigrationMetadata.Id
        {
            get { return "201507311833251_added seed method for articles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
