// <auto-generated />
namespace MikeIt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedupvotefield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedupvotefield));
        
        string IMigrationMetadata.Id
        {
            get { return "201508020525184_added upvote field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
